[package]
name = "flamelang"
version = "0.1.2"
edition = "2024"
description = "A statically typed, fast, and modern programming language built in Rust."
license = "ISC"
repository = "https://github.com/shoya-129/flame"
keywords = ["compiler", "flame", "language", "scripting"]
categories = ["command-line-utilities", "compilers"]
exclude = [
    "automation/",
    "docs/",
    "bin/",
    "scripts/",
    "flame-vscode-extension/"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enigo = "0.6.1"
sysinfo = "=0.30.0"
hidapi = "2"
serialport = "4"
nokhwa = { version = "0.10", features = ["input-native"] }
image = "0.25"
btleplug = "0.12.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
once_cell = "1.21"
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["blocking"] }
zip = "8.6.0"
