[package]
name = "automation"
version = "0.1.0"
edition = "2026"
type = "executable"

[dependencies]
std = "0.1.0"

[plugins]
rust = "./native"

[native-dependencies]
uuid = { version = "*", features = ["v4"] }
